### ISSUE TITLE
Feature: Incorporate new vendor water quality ratings tiers

### ISSUE THREAD

**Issue by jimbrig** [powwater/vendor_dashboard#88]
See [this slack message from Ellie](https://powwatertychobra.slack.com/archives/C01JDL820MA/p1620911082004600).

The tiers are broken out using the value for `TDS` in the `vendor_tests` database table:

<img width="418" alt="Screen Shot 2021-05-13 at 9 33 26 AM" src="https://user-images.githubusercontent.com/32652297/118145907-174c8580-b3dc-11eb-982d-beda6239ac09.png">

## Todo:

- [x] Add a new table to the database for `vendor_tests_rating_tiers` with columns: `min_tds`,  `max_tds`,  `rating`, and `html` where the rating is the numeric value and HTML will contain the text corresponding to the display of the numeric rating as the water droplets shown above.
- [x] Add the table as reference to the water quality tests module/tab (will keep non-editable for now), remembering to escape the HTML.
- [ ] Create a function/view to join the water quality tests by vendor with the tiers and calculate the test result's corresponding rating tier
- [x] Show the results from above in the water quality tests table in the app escaping the droplet's HTML.

**Comment by jimbrig** [comment]
For creating the water drop icon ratings divs see this code for reference:

## CSS:

```
.full {
  color: blue;
  vertical-align:text-bottom;
}

.half {
  color: blue;
  width: 5px;
  overflow: hidden;
  vertical-align:text-bottom;
  margin-right: 8px;
}
```

## HTML:

```
<!-- rating: 5 -->

<div class="rating-tint">
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
</div>

<!-- rating: 4.5 -->

<div class="rating-tint">
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint half"></span>
</div>

<!-- rating: 4 -->

<div class="rating-tint">
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span>
</div>

<!-- rating: 3.5 -->

<div class="rating-tint">
  <span class="fa fa-tint full"></span>
  <span class="fa fa-tint full"></span
  ><span class="fa fa-tint full"></span>
  <span class="fa fa-tint half"></span>
</div>
```
